import requests
import os
import resend
from datetime import datetime, timezone, timedelta

DEEPSEEK_KEY = os.environ.get("DEEPSEEK_API_KEY")
DEEPSEEK_URL = "https://api.deepseek.com/chat/completions"
RESEND_KEY = os.environ.get("RESEND_API_KEY")
TARGET = os.environ.get("TARGET_EMAIL")
BEIJING_TZ = timezone(timedelta(hours=8))

def ask_ai(prompt, max_tokens=800):
    if not DEEPSEEK_KEY:
        return "API key missing"
    headers = {
        "Authorization": f"Bearer {DEEPSEEK_KEY}",
        "Content-Type": "application/json"
    }
    data = {
        "model": "deepseek-chat",
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": max_tokens,
        "temperature": 0.7
    }
    try:
        resp = requests.post(DEEPSEEK_URL, headers=headers, json=data, timeout=60)
        if resp.status_code == 200:
            return resp.json()["choices"][0]["message"]["content"].strip()
        else:
            return f"API error: {resp.status_code} {resp.text[:200]}"
    except Exception as e:
        return f"Network error: {e}"

def send_email(html_body):
    if not RESEND_KEY or not TARGET:
        print("Email config missing")
        return
    resend.api_key = RESEND_KEY
    try:
        resend.Emails.send({
            "from": "AI Daily <onboarding@resend.dev>",
            "to": [TARGET],
            "subject": f"AI Daily Report - {datetime.now(BEIJING_TZ).strftime('%Y-%m-%d')}",
            "html": html_body
        })
        print("Email sent!")
    except Exception as e:
        print(f"Email failed: {e}")

today = datetime.now(BEIJING_TZ)
date_str = today.strftime("%Y-%m-%d %A")
print(f"Generating report for {date_str}...")

prompt_frontier = "Explain a cutting-edge AI technology or trend (2026), with a title \"Frontier\", under 300 words."
prompt_basics = "Explain a basic AI concept: Loss Function. Title \"Basics\", under 300 words."
prompt_job = "Introduce an AI career: Prompt Engineer. Title \"Career\", include role, skills, salary, advice, under 300 words."

frontier = ask_ai(prompt_frontier)
basics = ask_ai(prompt_basics)
job = ask_ai(prompt_job)

html = f"""
<html>
<body style="font-family: sans-serif; max-width: 700px; margin: 0 auto; padding: 20px; background: #f5f7fa;">
<div style="background: linear-gradient(135deg, #667eea, #764ba2); color: white; padding: 30px; border-radius: 12px 12px 0 0; text-align: center;">
<h1>AI Daily Report</h1><p style="margin: 8px 0 0;">{date_str}</p>
</div>
<div style="background: white; padding: 25px; border-radius: 0 0 12px 12px;">
<h2>Frontier</h2><p>{frontier}</p>
<h2>Basics</h2><p>{basics}</p>
<h2>Career</h2><p>{job}</p>
<hr><p style="color: #a0aec0; font-size: 12px; text-align: center;">Generated by AI</p>
</div>
</body>
</html>
"""

send_email(html)
print("Done.")
